# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IEEE488mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IEEE488InstrumentManager(object):
    def setupUi(self, IEEE488InstrumentManager):
        IEEE488InstrumentManager.setObjectName("IEEE488InstrumentManager")
        IEEE488InstrumentManager.setWindowModality(QtCore.Qt.NonModal)
        IEEE488InstrumentManager.resize(1102, 949)
        IEEE488InstrumentManager.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(IEEE488InstrumentManager)
        self.centralwidget.setObjectName("centralwidget")
        self.ScanButton = QtWidgets.QPushButton(self.centralwidget)
        self.ScanButton.setGeometry(QtCore.QRect(60, 250, 151, 41))
        self.ScanButton.setObjectName("ScanButton")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(10, 520, 75, 23))
        self.exitButton.setObjectName("exitButton")
        self.instrumentTableLabel = QtWidgets.QLabel(self.centralwidget)
        self.instrumentTableLabel.setGeometry(QtCore.QRect(50, 120, 211, 31))
        self.instrumentTableLabel.setObjectName("instrumentTableLabel")
        self.shared_visa_lib_label = QtWidgets.QLabel(self.centralwidget)
        self.shared_visa_lib_label.setGeometry(QtCore.QRect(60, 210, 671, 21))
        self.shared_visa_lib_label.setObjectName("shared_visa_lib_label")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(20, 10, 741, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.loadInstrumentButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadInstrumentButton.setGeometry(QtCore.QRect(230, 250, 151, 41))
        self.loadInstrumentButton.setObjectName("loadInstrumentButton")
        self.sharedLibraryLabel = QtWidgets.QLabel(self.centralwidget)
        self.sharedLibraryLabel.setGeometry(QtCore.QRect(60, 190, 181, 16))
        self.sharedLibraryLabel.setObjectName("sharedLibraryLabel")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(20, 10, 91, 91))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("idewerkslogo6 copy.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.instrumentcomboBox = QtWidgets.QComboBox(self.centralwidget)
        self.instrumentcomboBox.setGeometry(QtCore.QRect(60, 160, 321, 22))
        self.instrumentcomboBox.setObjectName("instrumentcomboBox")
        IEEE488InstrumentManager.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(IEEE488InstrumentManager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1102, 22))
        self.menubar.setObjectName("menubar")
        IEEE488InstrumentManager.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(IEEE488InstrumentManager)
        self.statusbar.setObjectName("statusbar")
        IEEE488InstrumentManager.setStatusBar(self.statusbar)

        self.retranslateUi(IEEE488InstrumentManager)
        QtCore.QMetaObject.connectSlotsByName(IEEE488InstrumentManager)

    def retranslateUi(self, IEEE488InstrumentManager):
        _translate = QtCore.QCoreApplication.translate
        IEEE488InstrumentManager.setWindowTitle(_translate("IEEE488InstrumentManager", "IEEE488 Instrument Manager v1.02"))
        self.ScanButton.setText(_translate("IEEE488InstrumentManager", "Instrument Scan"))
        self.exitButton.setText(_translate("IEEE488InstrumentManager", "EXIT"))
        self.instrumentTableLabel.setText(_translate("IEEE488InstrumentManager", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Active Instrument List</span></p></body></html>"))
        self.shared_visa_lib_label.setText(_translate("IEEE488InstrumentManager", "NaN"))
        self.title_label.setText(_translate("IEEE488InstrumentManager", "<html><head/><body><p align=\"center\">IEE488 Instrument Manager</p></body></html>"))
        self.loadInstrumentButton.setText(_translate("IEEE488InstrumentManager", "Load Instrument"))
        self.sharedLibraryLabel.setText(_translate("IEEE488InstrumentManager", "Active Shared Library:"))
